//! Tavola degli item, parte 3 di 4: scritture, rubriche, mazzi, video.
//!
//! Qui cadono tre delle cinque fiastre rotte: la sezione mancante, il GUARDIAN
//! oltre i 640 byte e il contratto oltre l'hard cap.

use crate::contract::Defect;
use crate::families::Family as F;
use crate::spec::*;
use kbs_core::PublicationState as S;

pub const V: &[Spec] = &[
    Spec {
        rel: "scritture/01-tesina-argomentazione.html",
        famiglia: F::Scritture,
        titolo: "Tesina argomentativa: scegliere una tesi difendibile",
        riassunto: "Il compito lungo, e la scelta che lo rende valutabile.",
        paragrafi: &[
            "Una tesina argomentativa si valuta sulla difendibilità della tesi, non sulla sua originalità. Una tesi che nessuno può smentire non è una tesi, è un auspicio.",
            "Il compito chiede tre righe di definizione prima dell'argomentazione, e la rubrica le pesa. Senza definizioni, l'argomentazione galleggia.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/02-divisibilita.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: la tesi deve essere smentibile. Se non c'è nessun fatto che possa smentirla, non c'è argomentazione, e il compito diventa un esercizio di stile.",
        obiettivi: "Scegliere una tesi smentibile e sostenerla con argomenti espliciti.",
        scala: "Livello 4: smentisce la propria tesi e la difende. Livello 3: sostiene la tesi. Livello 2: distingue tesi e argomento. Livello 1: scrive.",
        equivoci: "Non confondere una tesi smentibile con una tesi falsa: una tesi vera e smentibile si dimostra con fatti, non con reiterate.",
        esempio: "«I fattori primi non esistono» è una tesi da smentire; «esistono molti fattori primi» non lo è, perché niente la smentisce.",
        verifica: "Scrivi tre righe di definizione e una tesi, e indica quale fatto potrebbe smentirti.",
        limite: "Vale per tesi su argomenti circoscritti: una tesi sul futuro non è smentibile da un fatto noto.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_17_1",
            testo: "Una tesina si valuta sulla difendibilità della tesi, non sulla sua originalità.",
            ancora: Some("span-17-1"),
            testo_span: Some("Una tesina argomentativa si valuta sulla difendibilità della tesi, non sulla sua originalità. Una tesi che nessuno può smentire non è una tesi, è un auspicio."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "scritture/02-tema-di-argomentazione.html",
        famiglia: F::Scritture,
        titolo: "Tema di argomentazione a tempo chiuso",
        riassunto: "Il compito con risorse chiuse, che è l'unico su cui la tesi del progetto è misurata.",
        paragrafi: &[
            "Il tema si svolge in due ore, con il materiale consentito. Le risorse chiuse sono la condizione che rende confrontabili due gruppi classe: senza di esse, la differenza finale non distingue l'insegnamento dall'inizio.",
            "È la prova su cui la tesi di `kb-s` è formulata: un compito a risorse chiuse misura l'apprendimento, e la pratica assistita non lo misura.",
        ],
        stato: S::Archiviato,
        corso: CORSO_MATEMATICA,
        prerequisiti: &[],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: due ore e il materiale consentito. Ciò che si porta da fuori non è un vantaggio, è un'altra prova.",
        obiettivi: "Sostenere un argomento entro un tempo chiuso usando solo il materiale consentito.",
        scala: "Livello 4: sceglie il taglio e lo sostiene nel tempo. Livello 3: sostiene l'argomento. Livello 2: distingue argomento e descrizione. Livello 1: scrive.",
        equivoci: "Non confondere il tempo di scrittura con il tempo di ragionamento: un testo breve e argomentato vale più di un testo lungo e descrittivo.",
        esempio: "Il compito dell'anno scorso chiedeva di scegliere fra due tesi e sostenerne una. Il tempo è stato il vincolo che ha deciso la qualità, non la quantità.",
        verifica: "Svolgi il tema in due ore e annota l'ora in cui hai scelto la tesi: la scelta tardiva è il difetto più comune.",
        limite: "Vale per il tempo assegnato: un tema con una settimana in più misura qualità di documentazione, non argomentazione.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_18_1",
            testo: "Le risorse chiuse sono la condizione che rende confrontabili due gruppi classe.",
            ancora: Some("span-18-1"),
            testo_span: Some("Il tema si svolge in due ore, con il materiale consentito. Le risorse chiuse sono la condizione che rende confrontabili due gruppi classe: senza di esse, la differenza finale non distingue l'insegnamento dall'inizio."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "scritture/03-relazione-di-laboratorio.html",
        famiglia: F::Scritture,
        titolo: "Relazione di laboratorio: che cosa hai fatto e che cosa hai misurato",
        riassunto: "La relazione come atto di dichiarazione dei limiti, non come descrizione.",
        paragrafi: &[
            "La relazione dichiara il protocollo, i dati raccolti e le incognite. Una relazione che descrive solo i risultati non consente a nessuno di rifare la misura.",
            "La sezione delle incognite è quella che il docente legge per prima, perché è l'unica che dice che cosa del numero è affidabile.",
        ],
        stato: S::InCorso,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["laboratori/03-dataset-cocola.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: la relazione dichiara che cosa non è stato misurato. Se non c'è quella sezione, la misura non è riproducibile e la relazione non passa.",
        obiettivi: "Scrivere una relazione con protocollo, dati e incognite dichiarate.",
        scala: "Livello 4: le incognite dichiarate sono quelle che limitano davvero il numero. Livello 3: dichiara protocollo e incognite. Livello 2: descrive i risultati. Livello 1: scrive.",
        equivoci: "Non confondere «il risultato è buono» e «la misura è affidabile»: la prima è un numero, la seconda è una dichiarazione di limiti.",
        esempio: "La relazione del laboratorio dichiara tre incognite e una di esse pesa su metà del tempo misurato: dichiararla vale più che riportare la media.",
        verifica: "Scrivi la sezione delle incognite della relazione e indica quale di esse modifica la conclusione.",
        limite: "Vale per misure ripetibili: un protocollo che non si può ripetere non ha incognite da dichiarare, e questo è il problema più grave.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_19_1",
            testo: "Senza la sezione delle incognite, la misura non è riproducibile.",
            ancora: Some("span-19-1"),
            testo_span: Some("La sezione delle incognite è quella che il docente legge per prima, perché è l'unica che dice che cosa del numero è affidabile."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    // ── Fiastra rotta n. 1: il GUARDIAN oltre i 640 byte. Il troncamento
    //    taglia la coda, e la coda è il vincolo che lo studente deve leggere
    //    per primo. D7.
    Spec {
        rel: "scritture/04-sintesi-risposta-aperta.html",
        famiglia: F::Scritture,
        titolo: "Sintesi in risposta aperta",
        riassunto: "Unità con il GUARDIAN troppo lungo: la coda che il vincolo deve proteggere verrebbe tagliata.",
        paragrafi: &[
            "Questa unità chiede una sintesi di un testo di tre pagine in venti righe. Il compito è sensato e il materiale è adeguato.",
            "Il difetto non è nel contenuto ma nel contratto: il GUARDIAN è più lungo di quanto il formato possa garantirne.",
        ],
        stato: S::Bozza,
        corso: CORSO_MATEMATICA,
        prerequisiti: &[],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "La regola che lo studente deve applicare, enunciata per esteso, con i casi in cui vale e i casi in cui non vale, e con l'esempio del controesempio che la distingue dalla regola vicina. La regola che lo studente deve applicare, enunciata per esteso, con i casi in cui vale e i casi in cui non vale, e con l'esempio del controesempio che la distingue dalla regola vicina. La regola che lo studente deve applicare, enunciata per esteso, con i casi in cui vale e i casi in cui non vale, e con l'esempio del controesempio che la distingue dalla regola vicina.",
        obiettivi: "Sintetizzare un testo breve mantenendo la tesi principale e scartando gli esempi.",
        scala: "Livello 4: distingue la tesi dagli esempi e sa dire che cosa ha scartato. Livello 3: sintetizza correttamente. Livello 2: individua la tesi. Livello 1: riassume per paragrafi.",
        equivoci: "Non confondere sintesi e riassunto: la sintesi ricostruisce un ragionamento, il riassunto conserva l'ordine.",
        esempio: "Un testo di tre pagine su due interpretazioni della stessa definizione si sintetizza in tre righe: definizione, divergenza, conseguenza.",
        verifica: "Sintetizza il testo in venti righe e indica in una riga quale parte hai sacrificato.",
        limite: "Vale per testi argomentativi continui: un testo con elenchi si sintetizza per voce, non in prosa.",
        difetto: Defect::GuardianOltreBudget,
        claims: &[ClaimSpec {
            id: "cl_20_1",
            testo: "La sintesi ricostruisce un ragionamento, il riassunto conserva l'ordine.",
            ancora: Some("span-20-1"),
            testo_span: Some("Non confondere sintesi e riassunto: la sintesi ricostruisce un ragionamento, il riassunto conserva l'ordine."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "rubriche/01-rubrica-tesina.html",
        famiglia: F::Rubrica,
        titolo: "Rubrica della tesina, versione 2",
        riassunto: "La griglia che decide, e che dichiara la propria versione.",
        paragrafi: &[
            "La rubrica ha quattro descrittori e due livelli per ciascuno. Ogni livello descrive che cosa l'elaborato fa, e non che cosa dovrebbe fare.",
            "I punteggi sono ancorati al numero di righe e alla presenza delle definizioni: un elaborato con tesi e senza definizioni non può arrivare al livello alto, e il motivo è scritto.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["scritture/01-tesina-argomentazione.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: la rubrica è la versione 2. I voti dati con la versione 1 restano sotto la versione 1, e non si riinterpretano con la nuova.",
        obiettivi: "Applicare la rubrica e registrarne la versione accanto al voto.",
        scala: "Livello 4: sa quando un punteggio è anomalo rispetto alla rubrica. Livello 3: applica i descrittori. Livello 2: distingue i livelli. Livello 1: legge la griglia.",
        equivoci: "Non confondere il descrittore con il consiglio: un descrittore dice che cosa c'è, un consiglio dice che cosa fare.",
        esempio: "Il descrittore «la tesi è enunciata e difesa» vale per un elaborato che enuncia al primo paragrafo e difende alla fine: la posizione conta quanto la quantità.",
        verifica: "Applica la rubrica all'elaborato della tesina e giustifica il punteggio del descrittore più discusso.",
        limite: "Vale per gli elaborati di questa classe: la rubrica non è stata calibrata su altre scuole, e non lo dichiara essere.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_21_1",
            testo: "I voti dati con una versione di rubrica restano sotto quella versione.",
            ancora: Some("span-21-1"),
            testo_span: Some("La rubrica ha quattro descrittori e due livelli per ciascuno. Ogni livello descrive che cosa l'elaborato fa, e non che cosa dovrebbe fare."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "rubriche/02-rubrica-relazione.html",
        famiglia: F::Rubrica,
        titolo: "Rubrica della relazione di laboratorio",
        riassunto: "La griglia che pesa la dichiarazione delle incognite.",
        paragrafi: &[
            "Il descrittore con più peso è la dichiarazione delle incognite, e pesa più della completezza della descrizione del protocollo.",
            "È una scelta discussa: si potrebbe dare più peso alla riproducibilità. Chi valuta deve sapere che il peso è una scelta e non un fatto.",
        ],
        stato: S::DelDocente,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["scritture/03-relazione-di-laboratorio.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: se due relazioni descrivono lo stesso esperimento e una sola dichiara le incognite, la seconda ottiene un punteggio più alto. È la regola, ed è discutibile.",
        obiettivi: "Valutare una relazione distinguendo completezza e riproducibilità.",
        scala: "Livello 4: sa difendere il peso scelto e riconosce l'alternativa. Livello 3: distingue completezza e riproducibilità. Livello 2: usa i descrittori. Livello 1: legge la griglia.",
        equivoci: "Non confondere il peso di un descrittore con la sua importanza: il peso è una scelta del corso, e cambia da anno a anno.",
        esempio: "Due relazioni identiche nella descrizione e diverse nella dichiarazione delle incognite: 8 e 11 punti. La differenza è tutta lì.",
        verifica: "Valuta la relazione del laboratorio con la rubrica e indica quale descrittore hai pesato di più.",
        limite: "Vale per l'anno in corso: la rubrica non è stata calibrata con doppio correttore, e quindi i punteggi non sono ancora riproducibili fra persone.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_22_1",
            testo: "Il peso di un descrittore di rubrica è una scelta del corso, non un fatto.",
            ancora: Some("span-22-1"),
            testo_span: Some("È una scelta discussa: si potrebbe dare più peso alla riproducibilità. Chi valuta deve sapere che il peso è una scelta e non un fatto."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "mazzi/01-mazzo-frazioni.html",
        famiglia: F::Mazzi,
        titolo: "Mazzo di ripasso sulle frazioni",
        riassunto: "Il mazzo che lo studente amministra da sé, e che il sistema non programma.",
        paragrafi: &[
            "Il mazzo contiene quaranta carte: fronte con la domanda, retro con la risposta e la regola che la giustifica. Le carte sono ordinate per argomento, non per difficoltà.",
            "Il sistema non programma il ripasso e non sa quando lo studente è pronto. L'attività è autoregolata, e il mazzo è soltanto il materiale su cui la regolazione avviene.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["esercizi/01-somma-di-frazioni.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: il mazzo non sa quando sei pronto. Girare le carte è tuo compito, e nessun contatore nel sistema ti dice se hai studiato abbastanza.",
        obiettivi: "Usare il mazzo come materiale di ripasso e riconoscere che la regolazione è dello studente.",
        scala: "Livello 4: sa scegliere il momento di smettere e dire perché. Livello 3: usa il mazzo. Livello 2: conosce l'ordine degli argomenti. Livello 1: sfoglia le carte.",
        equivoci: "Non confondere il mazzo con il programma: il mazzo dice che cosa ripassare, non quando smettere.",
        esempio: "Dodici carte su quarantasette coprono la riduzione. Se sbagli sei su quelle dodici e non su le altre, il mazzo dice che cosa rileggere e non quando hai finito.",
        verifica: "Usa il mazzo e annota quali carte hai sbagliato al primo giro: sono il tuo programma, e il sistema non te lo dirà.",
        limite: "Vale per il ripasso per argomento: non tiene conto della dimenticanza nel tempo, che è ciò che distingue il ripasso dal riapprendimento.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_23_1",
            testo: "Il mazzo non sa quando lo studente è pronto a smettere.",
            ancora: Some("span-23-1"),
            testo_span: Some("Il sistema non programma il ripasso e non sa quando lo studente è pronto. L'attività è autoregolata, e il mazzo è soltanto il materiale su cui la regolazione avviene."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    // ── Questo mazzo è valido. Il difetto «oltre l'hard cap» che il banco
    //    verifica sta in `produzioni/02-podcast-di-classe.html`, dove il
    //    contenuto è banale: così la metà negativa di D7 non viene attribuita
    //    al pezzo di materiale più discusso del banco.
    Spec {
        rel: "mazzi/02-mazzo-storia.html",
        famiglia: F::Mazzi,
        titolo: "Mazzo di ripasso di storia",
        riassunto: "Il mazzo sulle date e sulle cause, e la regola di conservazione delle carte.",
        paragrafi: &[
            "Il mazzo raccoglie ventidue carte sulle date e sulle cause. Le carte sono brevi e citano la fonte in fondo.",
            "Le carte riportano la fonte in fondo, e la fonte è la parte che le rende verificabili: una carta senza fonte non entra nel mazzo.",
        ],
        stato: S::Bozza,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["scritture/02-tema-di-argomentazione.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: ogni carta riporta la fonte in fondo, e la fonte è la parte che rende la carta verificabile.",
        obiettivi: "Collegare una data alle cause, e distinguere cronologia e spiegazione.",
        scala: "Livello 4: distingue causa strutturale da causa immediata. Livello 3: collega le date alle cause. Livello 2: ordina gli eventi. Livello 1: sfoglia le carte.",
        equivoci: "Non confondere cronologia e spiegazione: sapere quando un fatto è avvenuto non spiega perché.",
        esempio: "La carta sulla crisi del 1929 porta la data e la causa immediata; quella sul dopoguerra porta la causa strutturale. Le due carte non si sostituiscono.",
        verifica: "Ordina le carte per anno e scegli le tre che dicono «perché» e non «quando».",
        limite: "Vale per la cronologia italiana del Novecento: le carte non coprono la storia mondiale, e il mazzo non lo dichiara su ogni carta.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_24_1",
            testo: "Sapere quando un fatto è avvenuto non spiega perché sia avvenuto.",
            ancora: Some("span-24-1"),
            testo_span: Some("Non confondere cronologia e spiegazione: sapere quando un fatto è avvenuto non spiega perché."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "video/01-diminuzione-derivate.html",
        famiglia: F::VideoAudio,
        titolo: "Video: la diminuzione di una derivata",
        riassunto: "Che cosa entra nell'indice di un video, e che cosa resta fuori.",
        paragrafi: &[
            "Di un video entra nell'indice la trascrizione con i suoi timestamp, e nient'altro. La relazione spaziale fra ciò che il docente indica e quello che dice resta fuori, perché non è testo.",
            "È il punto debole dichiarato del catalogo: un video è recuperabile e resta passivo. Il testo non manca; manca quello che rendeva il video interessante.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/01-numero-razionale.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: la trascrizione è tutto ciò che questo sistema vedrà del video. Se il passaggio importante è un gesto, quel passaggio non esiste per l'indice.",
        obiettivi: "Leggere la trascrizione segmentata e riconoscere ciò che il video non comunica al sistema.",
        scala: "Livello 4: sa dire quale passaggio si perde nella trascrizione. Livello 3: usa i timestamp. Livello 2: legge la trascrizione. Livello 1: guarda il video.",
        equivoci: "Non confondere «il video è stato trascritto» e «il video è stato capito»: la trascrizione è una forma, non un grado di comprensione.",
        esempio: "Il docente scrive al.Writer la segno della funzione: la trascrizione dice «la segno della funzione» e non sa che è stato scritto un simbolo.",
        verifica: "Guarda il video, poi leggi la trascrizione e indica il passaggio che solo il video communicates.",
        limite: "Vale per video con docente parlante: un video muto con testo a schermo non è coperto da questa regola e non è coperto dal banco.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_25_1",
            testo: "Di un video entra nell'indice la trascrizione, e non la relazione spaziale.",
            ancora: Some("span-25-1"),
            testo_span: Some("Di un video entra nell'indice la trascrizione con i suoi timestamp, e nient'altro. La relazione spaziale fra ciò che il docente indica e quello che dice resta fuori, perché non è testo."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    // ── Fiastra rotta n. 2: manca la sezione LIMITE delle otto obbligatorie.
    //    Un contratto con sette sezioni non è un contratto: è un contratto a cui
    //    manca la dichiarazione di che cosa non vale. D7.
    Spec {
        rel: "video/02-lezione-trascritta.html",
        famiglia: F::VideoAudio,
        titolo: "Trascrizione della lezione sulle funzioni",
        riassunto: "Unità con sette sezioni su otto: manca la dichiarazione di che cosa non vale.",
        paragrafi: &[
            "La trascrizione è segmentata in quarantasei frammenti, ciascuno con il suo tempo. I frammenti sono leggibili e riordinabili.",
            "Al contratto manca la sezione che dice che cosa questa lezione non copre. Un contratto a cui manca quella sezione non dice al lettore che cosa non sta imparando.",
        ],
        stato: S::Bozza,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["video/01-diminuzione-derivate.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: i frammenti sono in ordine di tempo e non di argomento. Se cerchi un tema, cerca nei titoli e non nel testo.",
        obiettivi: "Leggere una trascrizione segmentata e ricostruire l'ordine degli argomenti.",
        scala: "Livello 4: ricostruisce l'ordine degli argomenti dai titoli dei frammenti. Livello 3: usa i timestamp. Livello 2: legge i frammenti. Livello 1: guarda il video.",
        equivoci: "Non confondere l'ordine dei frammenti con l'ordine degli argomenti: il docente ha cambiato argomento tre volte.",
        esempio: "I frammenti 12, 19 e 33 trattano la stessa funzione con tre esempi diversi, e sono separati da venti minuti di altro argomento.",
        verifica: "Ricostruisce la scaletta della lezione e indica quale argomento occupa più tempo.",
        limite: "Vale per la lezione registrata: la trascrizione non distingue ciò che il docente ha detto e ciò che ha solo scritto.",
        difetto: Defect::SezioneMancante("LIMITE"),
        claims: &[ClaimSpec {
            id: "cl_26_1",
            testo: "I frammenti della trascrizione sono in ordine di tempo, non di argomento.",
            ancora: Some("span-26-1"),
            testo_span: Some("La trascrizione è segmentata in quarantasei frammenti, ciascuno con il suo tempo. I frammenti sono leggibili e riordinabili."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "video/03-audio-glossario.html",
        famiglia: F::VideoAudio,
        titolo: "Audio-glossario: i termini in ordine di uso",
        riassunto: "Il glossario che cresce con le domande, e chi decide quando fermarlo.",
        paragrafi: &[
            "Ogni scheda del glossario contiene il termine, la definizione in una frase e un esempio tratto dalle lezioni precedenti.",
            "Il glossario cresce quando una domanda ricorre. Chi decide che una domanda è ricorrente è il docente, e la soglia che usa è dichiarata qui: cinque domande sullo stesso termine in due settimane.",
        ],
        stato: S::DelDocente,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["scritture/03-relazione-di-laboratorio.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: «ricorrente» è una parola che significa una cosa sola, ed è la soglia dichiarata sopra. Se pensavi a un'altra soglia, questa scheda non parla della tua.",
        obiettivi: "Scrivere la definizione di un termine in una frase, con un esempio tratto dal proprio corso.",
        scala: "Livello 4: distingue definizione e esempio, e sa quando il termine non serve. Livello 3: scrive la scheda. Livello 2: riconosce il termine. Livello 1: ascolta.",
        equivoci: "Non confondere una definizione con un esempio: l'esempio mostra il termine in uso e non lo definisce.",
        esempio: "«Commutatività: il risultato non dipende dall'ordine. Nella somma 3+5 dà 8 come 5+3.» La seconda frase è un esempio e non aggiunge alla prima.",
        verifica: "Scrivi la scheda del termine che ti ha fermato più spesso e verifica che la definizione stia nella prima frase.",
        limite: "Vale per i termini che ricorrono almeno cinque volte in due settimane: gli altri non entrano, e questa è una scelta del corso.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_27_1",
            testo: "La soglia di ricorrenza che fa crescere il glossario è dichiarata nella scheda.",
            ancora: Some("span-27-1"),
            testo_span: Some("Il glossario cresce quando una domanda ricorre. Chi decide che una domanda è ricorrente è il docente, e la soglia che usa è dichiarata qui: cinque domande sullo stesso termine in due settimane."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
];
