//! Tavola degli item, parte 2 di 4: esercizi, laboratori, prove.

use crate::contract::Defect;
use crate::families::Family as F;
use crate::spec::*;
use kbs_core::{GraderKind, PublicationState as S};

pub const V: &[Spec] = &[
    Spec {
        rel: "esercizi/02-proporzioni.html",
        famiglia: F::Esercizi,
        titolo: "Proporzioni e proprietà delle proporzioni",
        riassunto: "Che cosa è lecito fare con un'uguaglianza di rapporti senza discuterne la verità.",
        paragrafi: &[
            "In una proporzione a/b = c/d si possono moltiplicare o dividere in croce i due membri: la relazione resta vera qualunque sia il valore.",
            "Quello che non si può fare è dividere per un termine che sia zero: la divisione per zero non è definita e invalida tutta la catena di passaggi.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/01-numero-razionale.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: moltiplicare in croce è sempre lecito. Dividere per un termine nullo non lo è mai, e la catena di passaggi vale solo se ogni divisione è lecita.",
        obiettivi: "Applicare le proprietà delle proporzioni e riconoscere i passaggi non leciti.",
        scala: "Livello 4: riconosce il passaggio non lecito e lo spiega. Livello 3: applica correttamente. Livello 2: moltiplica in croce. Livello 1: risolve con la regola dei tre.",
        equivoci: "Non confondere proprietà delle proporzioni con proprietà delle equazioni: si può moltiplicare in croce, non si può sommare in croce.",
        esempio: "Se 3 corrisponde a 5 e 7 corrisponde a x, allora 3·x = 5·7, quindi x = 35/3. Ma se al posto di 3 ci fosse 0, la proporzione non avrebbe soluzione.",
        verifica: "Risolvi le due proporzioni dell'esercizio e indica per quale passaggio il risultato perde significato.",
        limite: "Vale per rapporti di numeri reali non nulli; non si estende a rapporti di vettori.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_06_1",
            testo: "Dividere per un termine nullo invalida la catena dei passaggi.",
            ancora: Some("span-06-1"),
            testo_span: Some("Quello che non si può fare è dividere per un termine che sia zero: la divisione per zero non è definita e invalida tutta la catena di passaggi."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[ExerciseSpec {
            id: "ex_06_1",
            famiglia: "proporzione-diretta",
            generatore: "kbs-exercise/0.1.0",
            testo: "Il rapporto a/b vale quanto c/d: ricava d sapendo a, b, c, tutti non nulli.",
            checker: CheckerSpec::Numeric { tolerance: 0.0001 },
            istanze: &[InstanceSpec { seed: "s1", a: 3, b: 5, c: 7, attesa: "11.666666666666666" }],
            giudicato_da: Some(GraderKind::Deterministic),
        }],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "esercizi/03-scelta-multipla-frazioni.html",
        famiglia: F::Esercizi,
        titolo: "Scelta multipla sulla riduzione",
        riassunto: "Quattro alternative, una sola esatta, e il checker che confronta la posizione.",
        paragrafi: &[
            "Nella scelta multipla il checker confronta la posizione dell'alternativa esatta, non il testo: le alternative possono essere riscritte senza che l'esercizio cambi.",
            "È il caso più economico di verifica deterministica, e anche il più fragile: se le alternative cambiano ordine senza che l'indice cambi, la risposta esatta cambia sotto gli occhi di chi l'ha già fatta.",
        ],
        stato: S::DelDocente,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["esercizi/01-somma-di-frazioni.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: l'indice dell'alternativa esatta fa parte del testo dell'esercizio. Se le alternative si riordinano, l'esercizio è un altro esercizio.",
        obiettivi: "Scegliere l'alternativa esatta e giustificare la scelta con una riduzione.",
        scala: "Livello 4: giustifica anche perché le altre sono sbagliate. Livello 3: sceglie correttamente. Livello 2: riduce a candidates. Livello 1: indovina.",
        equivoci: "Non confondere la posizione con il testo dell'alternativa, e non credere che l'ordine delle opzioni sia irrilevante.",
        esempio: "Alla domanda «qual è la forma ridotta di 18/24?» le alternative 3/4, 6/8, 9/12 e 12/16 contengono una sola risposta esatta: 3/4. Le altre sono equivalenti alla risposta ma non ridotte.",
        verifica: "Rispondi all'esercizio e indica quale alternativa è equivalente ma non in forma ridotta.",
        limite: "La posizione esatta vale finché le opzioni non vengono riordinate: l'esercizio non è autosufficiente dopo un riordino.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_07_1",
            testo: "Il checker della scelta multipla confronta la posizione, non il testo dell'alternativa.",
            ancora: Some("span-07-1"),
            testo_span: Some("Nella scelta multipla il checker confronta la posizione dell'alternativa esatta, non il testo: le alternative possono essere riscritte senza che l'esercizio cambi."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[ExerciseSpec {
            id: "ex_07_1",
            famiglia: "scelta-multipla-riduzione",
            generatore: "kbs-exercise/0.1.0",
            testo: "Qual è la forma ridotta della frazione data? Le alternative sono tutte equivalenti a una sola.",
            checker: CheckerSpec::MultipleChoice {
                corretta: 0,
                opzioni: &["3/4", "6/8", "9/12", "12/16"],
            },
            istanze: &[InstanceSpec { seed: "s1", a: 18, b: 24, c: 4, attesa: "0" }],
            giudicato_da: Some(GraderKind::Deterministic),
        }],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "esercizi/04-algoritmo-euclide.html",
        famiglia: F::Esercizi,
        titolo: "Algoritmo di Euclide e forma normale esplicita",
        riassunto: "Il MCD calcolato con l'algoritmo delle divisioni, e un checker che non è un parser di espressioni.",
        paragrafi: &[
            "L'algoritmo di Euclide calcola il massimo comune divisore ripetendo la divisione: l'ultimo resto non nullo è il MCD.",
            "Il checker di questa unità non interpreta espressioni: confronta con una forma normale dichiarata dal generatore. Un parser che decide le risposte è il modo più rapido per costruire un sistema che sbaglia con sicurezza.",
        ],
        stato: S::InCorso,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["letture/02-divisibilita.html"],
        origine: OriginSpec::Generated {
            by: DOCENTE_2,
            model: "claude-sonnet-4-5",
            prompt_hash: "sha256:77bc02e9a1ff",
            generator: "kbs-intake/0.1.0",
        },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: il MCD si calcola con l'algoritmo delle divisioni, non scomponendo in fattori primi quando i numeri sono grandi. Il checker confronta una forma normale dichiarata: non valuta.",
        obiettivi: "Calcolare il MCD con l'algoritmo di Euclide e riconoscere la forma normale dichiarata.",
        scala: "Livello 4: sa perché la forma normale basta e quando non basta. Livello 3: calcola il MCD. Livello 2: esegue una divisione. Livello 1: scompone in fattori primi.",
        equivoci: "Non confondere MCD e mcm, e non credere che due espressioni equivalenti abbiano la stessa forma normale dichiarata.",
        esempio: "MCD(462, 1071): 1071 = 2·462 + 147, 462 = 3·147 + 21, 147 = 7·21 + 0. L'ultimo resto non nullo è 21.",
        verifica: "Calcola il MCD dell'istanza dell'esercizio con l'algoritmo e confronta con la forma normale dichiarata dal generatore.",
        limite: "L'algoritmo è definito per interi non negativi: con zero dà il divisore, con negativi dà il MCD dei valori assoluti.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_08_1",
            testo: "Il checker non interpreta espressioni: confronta una forma normale dichiarata.",
            ancora: Some("span-08-1"),
            testo_span: Some("Il checker di questa unità non interpreta espressioni: confronta con una forma normale dichiarata dal generatore. Un parser che decide le risposte è il modo più rapido per costruire un sistema che sbaglia con sicurezza."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[ExerciseSpec {
            id: "ex_08_1",
            famiglia: "mcd-euclide",
            generatore: "kbs-exercise/0.1.0",
            testo: "Calcola il MCD di a·b e di a·c con l'algoritmo di Euclide e riporta la forma normale dichiarata.",
            checker: CheckerSpec::Equivalence { normale: "mcd-normale" },
            istanze: &[InstanceSpec { seed: "s1", a: 462, b: 462, c: 1, attesa: "462" }],
            giudicato_da: Some(GraderKind::Deterministic),
        }],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "esercizi/05-differenza-di-insiemi.html",
        famiglia: F::Esercizi,
        titolo: "Differenza di insiemi e controllo della risposta",
        riassunto: "Un esercizio archiviato: resta leggibile a chi lo ha seguito, e non è più citabile.",
        paragrafi: &[
            "La differenza A − B è l'insieme degli elementi di A che non sono in B. Si scrive anche A \\ B, e la barra all'indietro non è una divisione.",
            "L'unità è archiviata: chi l'aveva già in carico la vede ancora, e nessuno la cita come fonte attuale. È la differenza fra conservare e pubblicare.",
        ],
        stato: S::Archiviato,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/03-frazione-irriducibile.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: A − B non è A divisa per B. Se l'insieme B contiene tutto A, allora A − B è vuoto, e un insieme vuoto non ha cardinalità zero per definizione sbagliata.",
        obiettivi: "Calcolare la differenza di due insiemi e controllare il risultato con l'insieme complementare.",
        scala: "Livello 4: controlla con il complementare. Livello 3: calcola la differenza. Livello 2: elenca gli elementi di A. Livello 1: confonde la differenza con la divisione.",
        equivoci: "Non confondere A − B con B − A, e non leggere la barra all'indietro come una divisione.",
        esempio: "A = {1, 2, 3}, B = {2, 4}. A − B = {1, 3}. Con A − A si ottiene l'insieme vuoto, che non coincide con 0.",
        verifica: "Calcola la differenza dell'istanza e verifica che (A − B) ∩ B sia vuoto.",
        limite: "Vale per insiemi finiti rappresentati esplicitamente: la differenza di insiemi infiniti non si calcola per elencazione.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_09_1",
            testo: "A − A è l'insieme vuoto, e non il numero zero.",
            ancora: Some("span-09-1"),
            testo_span: Some("La differenza A − B è l'insieme degli elementi di A che non sono in B. Si scrive anche A \\ B, e la barra all'indietro non è una divisione."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[ExerciseSpec {
            id: "ex_09_1",
            famiglia: "differenza-insiemi",
            generatore: "kbs-exercise/0.1.0",
            testo: "Dato l'insieme {a, b, c} e l'insieme {b, d}, scrivi la differenza come insieme ordinato.",
            checker: CheckerSpec::Set { elementi: &["a", "c"] },
            istanze: &[InstanceSpec { seed: "s1", a: 1, b: 2, c: 3, attesa: "{a, c}" }],
            giudicato_da: Some(GraderKind::Deterministic),
        }],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "esercizi/06-prova-aperta.html",
        famiglia: F::Esercizi,
        titolo: "Prova aperta senza verificatore",
        riassunto: "L'esercizio che non può entrare nel percorso di pubblicazione, e perché.",
        paragrafi: &[
            "Questo esercizio non ha un verificatore deterministico: la risposta è un testo, e un testo non ha una forma normale con cui confrontarla.",
            "Un esercizio senza verificatore non entra nel percorso di pubblicazione. Può restare speculativo per lo studente che lo incontra, e non può diventare parte dell'indice condiviso.",
        ],
        stato: S::DelDocente,
        corso: CORSO_MATEMATICA,
        prerequisiti: &[],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: questo esercizio non ha un verificatore, e quindi non è valutabile in modo deterministico. Va svolto e giudicato da una persona, non dal codice.",
        obiettivi: "Riconoscere che la catena di grading è deterministico, poi pari, poi umano, e che senza il primo gradino l'unità non pubblica.",
        scala: "Livello 4: sa dire quale dei tre gradini manca. Livello 3: distingue il grading umano dal deterministico. Livello 2: sa che serve un giudizio. Livello 1: risponde.",
        equivoci: "Non confondere «non verificabile» con «sbagliato»: la mancanza del checker è un fatto del materiale, non un voto.",
        esempio: "«Spiega perché la somma converge» ha risposte diverse e tutte plausibili: nessun confronto deterministico è possibile senza ridurre il testo a una forma.",
        verifica: "Indica quale dei tre gradini della catena di grading può valutare questo esercizio, e perché gli altri due no.",
        limite: "Vale finché l'esercizio è a risposta aperta: un checker deterministico qui sarebbe un giudizio mascherato da programma.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_10_1",
            testo: "Un esercizio senza verificatore deterministico non entra nel percorso di pubblicazione.",
            ancora: Some("span-10-1"),
            testo_span: Some("Un esercizio senza verificatore non entra nel percorso di pubblicazione. Può restare speculativo per lo studente che lo incontra, e non può diventare parte dell'indice condiviso."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "laboratori/01-notebook-frazioni.html",
        famiglia: F::Laboratori,
        titolo: "Notebook: ridurre e rappresentare",
        riassunto: "Il laboratorio che produce l'errore: una claim che il foglio non sostiene.",
        paragrafi: &[
            "Il foglio calcola la riduzione di trenta frazioni e rappresenta ogni risultato come punto sul piano. La riduzione è corretta; la conclusione che il foglio ne ricava non lo è.",
            "È il caso più interessante del banco: l'affermazione c'è, ha un punto d'appoggio nel documento, e il punto d'appoggio non la regge. L'affermazione resta nel registro con la sua traccia, e non esce dall'output.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["esercizi/01-somma-di-frazioni.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: un errore nel foglio non è un errore nell'unità. Il foglio resta e l'affermazione che non regge resta con la sua traccia, perché un registro che cancella i propri errori non è un registro.",
        obiettivi: "Riconoscere una claim che il proprio documento non sostiene e distinguerla da una claim falsa.",
        scala: "Livello 4: distingue claim falsa e claim non sostenuta. Livello 3: riconosce che lo span non regge. Livello 2: legge lo span. Livello 1: esegue il foglio.",
        equivoci: "Non confondere «lo span non sostiene la claim» con «la claim è falsa»: la prima è un difetto del documento, la seconda della proposizione.",
        esempio: "Il foglio afferma che ridurre aumenta il valore assoluto del denominatore. Ridurre divide entrambi per un fattore comune, quindi lo diminuisce o lo lascia invariato.",
        verifica: "Indica quale delle due affermazioni del foglio è sostenuta dallo span e quale no, e correggi la seconda.",
        limite: "Vale per affermazioni con un solo span: un'affermazione che poggia su più parti del documento non è giudicabile da una coppia sola.",
        difetto: Defect::Nessuno,
        claims: &[
            ClaimSpec {
                id: "cl_11_1",
                testo: "Ridurre una frazione diminuisce il denominatore o lo lascia invariato.",
                ancora: Some("span-11-1"),
                testo_span: Some("Il foglio calcola la riduzione di trenta frazioni e rappresenta ogni risultato come punto sul piano. La riduzione è corretta; la conclusione che il foglio ne ricava non lo è."),
                stato: ClaimStatusKind::Contradicted,
                emittente: EmittenteSpec::DaLavoro { osservazione: "obs_11_1" },
            },
            ClaimSpec {
                id: "cl_11_2",
                testo: "Il limite di una successione si legge dal primo termine non nullo.",
                ancora: None,
                testo_span: None,
                stato: ClaimStatusKind::Unciteable,
                emittente: EmittenteSpec::Contenuto,
            },
        ],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "laboratori/02-simulazione-moneta.html",
        famiglia: F::Laboratori,
        titolo: "Simulazione della moneta: procedura casuale",
        riassunto: "Pubblicata ma non ratificata: leggibile, e non citabile.",
        paragrafi: &[
            "Il laboratorio genera sequenze di lanci ripetuti e conta quante volte esce testa. La simulazione serve a illustrare la convergenza empirica alla probabilità, non a dimostrare nulla.",
            "L'unità è in uso e non è ratificata. Il percorso di pubblicazione prevede la ratifica, e senza ratifica l'unità resta leggibile ma non citabile: è la regola che distingue le due cose.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/04-limite-di-successione.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: una simulazione illustra, non dimostra. La frequenza relativa osservata si avvicina alla probabilità, e la convergenza è un fatto asintotico che nessun numero di lanci rende esatto.",
        obiettivi: "Leggere una frequenza relativa e distinguere un'osservazione da una dimostrazione.",
        scala: "Livello 4: distingue illustrazione e dimostrazione. Livello 3: interpreta la frequenza relativa. Livello 2: conta i lanci. Livello 1: esegue la simulazione.",
        equivoci: "Non confondere frequenza relativa osservata e probabilità teorica: sono numeri diversi che tendono a coincidere.",
        esempio: "Su mille lanci si osservano 498 teste. La frequenza relativa è 0,498, e la probabilità teorica è 0,5: la differenza è attesa e non è un errore.",
        verifica: "Confronta la frequenza relativa di due simulazioni da mille lanci e spiega perché differiscono.",
        limite: "Vale per lanci indipendenti: con monete sbilanciate la frequenza relativa converge a una costante diversa da 1/2.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_12_1",
            testo: "La frequenza relativa osservata converge alla probabilità teorica al crescere dei lanci.",
            ancora: Some("span-12-1"),
            testo_span: Some("Il laboratorio genera sequenze di lanci ripetuti e conta quante volte esce testa. La simulazione serve a illustrare la convergenza empirica alla probabilità, non a dimostrare nulla."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "laboratori/03-dataset-cocola.html",
        famiglia: F::Laboratori,
        titolo: "Dataset: code a confronto",
        riassunto: "Il laboratorio che misura, e che dice che cosa non ha misurato.",
        paragrafi: &[
            "Il foglio confronta tre implementazioni di una coda circolare su insiemi di dati di grandezza diversa e registra il tempo di esecuzione.",
            "Il foglio dichiara cosa non ha misurato: risoluzione del timer, garbage collector, ordine di esecuzione. Una misura senza le sue incognite dichiarate non è una misura, è un numero.",
        ],
        stato: S::InCorso,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["esercizi/04-algoritmo-euclide.html"],
        origine: OriginSpec::Generated {
            by: DOCENTE_2,
            model: "claude-sonnet-4-5",
            prompt_hash: "sha256:0e5b71da44cc",
            generator: "kbs-intake/0.1.0",
        },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: un tempo di esecuzione misurato senza dire la risoluzione del timer e senza dire quante volte è stato ripetuto non dimostra niente. Il foglio dichiara le sue incognite prima di pubblicare i numeri.",
        obiettivi: "Leggere un confronto di prestazioni e riconoscere le incognite non dichiarate.",
        scala: "Livello 4: progetta il protocollo di misura. Livello 3: legge il confronto e le incognite. Livello 2: sa che cosa misura il timer. Livello 1: esegue il foglio.",
        equivoci: "Non confondere «più veloce in questo esperimento» e «più veloce»: la prima è un fatto, la seconda una generalizzazione.",
        esempio: "L'implementazione con ricerca lineare batte quella con indice su 10 000 elementi e perde su 1 000 000: la soglia di cambio di comportamento è il fatto, non la vittoria assoluta.",
        verifica: "Indica quale delle tre incognite dichiarate pesa di più sul risultato, e motivi la scelta.",
        limite: "Vale per la macchina e per il compilatore usati nel laboratorio: un altro ambiente richiede una nuova misura, non un'estrapolazione.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_13_1",
            testo: "Il laboratorio dichiara le incognite della misura prima di pubblicare i numeri.",
            ancora: Some("span-13-1"),
            testo_span: Some("Il foglio dichiara cosa non ha misurato: risoluzione del timer, garbage collector, ordine di esecuzione. Una misura senza le sue incognite dichiarate non è una misura, è un numero."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "prove/01-prova-parziale.html",
        famiglia: F::Prove,
        titolo: "Prova parziale: l'archivio che si auto-diagnostica",
        riassunto: "Le risposte degli anni passati dicono da sole dove la classe sbaglia.",
        paragrafi: &[
            "L'archivio conserva le risposte di tre edizioni della prova, raggruppate per item. Ogni item ha la sua distribuzione, e le distribuzioni dicono quale argomento cade a livello di classe.",
            "È l'unico oggetto del catalogo che si auto-diagnostica: non serve chiedere alla classe, perché i dati ci sono già e rispondono da soli.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["esercizi/02-proporzioni.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: la matrice risposta-per-studente è un dato personale e non può essere pubblicata. Quello che si pubblica è la distribuzione aggregata, e solo se il numero di studenti che sbaglia raggiunge la soglia.",
        obiettivi: "Legere una distribuzione di risposte e stabilire se un argomento cade a livello di classe.",
        scala: "Livello 4: distingue il segnale aggregato dal dato individuale. Livello 3: legge la distribuzione. Livello 2: conta le risposte. Livello 1: apre l'archivio.",
        equivoci: "Non confondere «l'item più sbagliato» e «l'argomento non spiegato»: l'item può essere ambiguo e l'argomento può essere chiaro.",
        esempio: "L'item sulla riduzione ha il 62% di risposte corrette, la media della prova è il 71%: l'argomento cade, e non lo deduce nessuno studente da solo.",
        verifica: "Indica quali due item della distribuzione suggeriscono l'argomento in caduta e spiega il criterio che hai usato.",
        limite: "Vale per item con un numero di risposte sufficiente: sotto la soglia il segnale non viene aggregato e non viene pubblicato.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_14_1",
            testo: "La distribuzione delle risposte di un item dice quale argomento cade a livello di classe.",
            ancora: Some("span-14-1"),
            testo_span: Some("L'archivio conserva le risposte di tre edizioni della prova, raggruppate per item. Ogni item ha la sua distribuzione, e le distribuzioni dicono quale argomento cade a livello di classe."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "prove/02-prova-finale.html",
        famiglia: F::Prove,
        titolo: "Prova finale: la ratifica superata dal contratto",
        riassunto: "L'unità la cui ratifica non vale più, perché il contratto è cambiato dopo.",
        paragrafi: &[
            "L'unità era ratificata. Poi il contratto è stato corretto: la sezione dei prerequisiti elencava un argomento che non era più richiesto.",
            "La ratifica vale per l'hash del contratto al momento in cui è stata firmata, e non per l'hash di oggi. Il docente che l'ha firmata non può aver valutato un testo diverso dal corrente.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["prove/01-prova-parziale.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Stale,
        guardian: "Prima di leggere: questo contratto è stato modificato dopo la ratifica. Finché il docente non firma di nuovo, l'unità non è citabile, e il motivo è visibile nel registro.",
        obiettivi: "Riconoscere quando una ratifica non vale più e che cosa va rifatto quando succede.",
        scala: "Livello 4: sa che cosa invalida la ratifica e come rimediare. Livello 3: riconosce la ratifica superata. Livello 2: sa che esiste una ratifica. Livello 1: apre l'unità.",
        equivoci: "Non confondere «ratifica superata» e «ratifica revocata»: la prima dipende da un fatto automatico, la seconda da una decisione.",
        esempio: "Ratificato sull'hash h1, contratto aggiornato a h2: l'unità resta in uso e leggibile, e non è più citabile finché l'hash non torna a coincidere.",
        verifica: "Indica quale fatto ha reso superflua la ratifica e quale atto la ripristina.",
        limite: "Vale finché il contratto è l'unica cosa ratificata: un'altra parte del documento che cambia non invalida nulla.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_15_1",
            testo: "La ratifica vale per l'hash del contratto al momento della firma.",
            ancora: Some("span-15-1"),
            testo_span: Some("La ratifica vale per l'hash del contratto al momento in cui è stata firmata, e non per l'hash di oggi. Il docente che l'ha firmata non può aver valutato un testo diverso dal corrente."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "prove/03-griglia-rubrica.html",
        famiglia: F::Prove,
        titolo: "Griglia di correzione della prova finale",
        riassunto: "La griglia che rende un voto riproducibile, e che le versioni non possono condividere.",
        paragrafi: &[
            "La griglia dichiara i descrittori di livello e i punteggi per ciascuno. Un voto senza griglia non è riproducibile: due correttori danno due voti e non si può sapere perché.",
            "Due versioni della griglia non possono condividere la stessa scala senza perderne il significato, perché i numeri hanno valori diversi.",
        ],
        stato: S::Archiviato,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/02-divisibilita.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: un voto senza la versione della rubrica con cui è stato assegnato non è riproducibile. Il numero da solo non dice nulla.",
        obiettivi: "Assegnare un voto con la griglia e registrarne la versione.",
        scala: "Livello 4: distingue le versioni e il loro effetto sui voti storici. Livello 3: assegna un voto con la griglia. Livello 2: conosce i descrittori. Livello 1: legge la griglia.",
        equivoci: "Non confondere il voto e la versione della rubrica: il voto è un numero, la versione dice che cosa quel numero significava.",
        esempio: "Il 7/100 della versione 1 e il 7/100 della versione 2 non corrispondono alla stessa qualità: la versione 2 ha alzato i descrittori del livello sufficiente.",
        verifica: "Assegna un voto all'elaborato dell'esercizio e registra la versione di rubrica usata.",
        limite: "Vale per i descrittori dichiarati nella versione corrente: le elaborati valutati con la versione 1 restano valutati con la versione 1.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_16_1",
            testo: "Due versioni di rubrica non possono condividere una scala senza perderne il significato.",
            ancora: Some("span-16-1"),
            testo_span: Some("Due versioni della griglia non possono condividere la stessa scala senza perderne il significato, perché i numeri hanno valori diversi."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
];
