//! Tavola degli item, parte 1 di 4: letture, esercizi.
//!
//! Le voci sono in ordine di `rel_path`, che è l'ordine in cui la pipeline le
//! ingerisce e che rende deterministico il referto.

use crate::contract::Defect;
use crate::families::Family as F;
use crate::spec::*;
use kbs_core::{GraderKind, PublicationState as S};

pub const V: &[Spec] = &[
    Spec {
        rel: "letture/01-numero-razionale.html",
        famiglia: F::Letture,
        titolo: "Il numero razionale come coppia",
        riassunto: "Che cosa distingue un razionale da un intero: la coppia di interi e la sua equivalenza.",
        paragrafi: &[
            "Un razionale si scrive come coppia di interi: il numeratore dice quante parti si prendono, il denominatore in quante parti uguali il primo intero era diviso.",
            "La stessa quantità ha molte rappresentazioni: 3/6, 2/4 e 1/2 indicano la stessa parte. La notazione in forma ridotta è quella in cui numeratore e denominatore non hanno divisori comuni.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &[],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: due interi con denominatore diverso non si sommano mai per semplice addizione delle coppie. Il banco di prova di questa unità usa coppie ridotte, e ridurre è il primo passo obbligatorio di ogni esercizio.",
        obiettivi: "Riconoscere l'equivalenza fra due coppie e ridurre una frazione ai minimi termini.",
        scala: "Livello 4: riduce e spiega perché la forma ridotta è unica. Livello 3: riduce senza spiegare. Livello 2: riconosce l'equivalenza senza ridurre. Livello 1: procede per tentativi.",
        equivoci: "Non confondere «ridurre» con «semplificare il segno»: −3/6 è −1/2, non 1/2. E non confondere la divisione delle coppie con una divisione fra numeratori.",
        esempio: "24/36 ha divisore comune 12: 24/12 = 2 e 36/12 = 3, quindi 24/36 = 2/3. Il divisore comune cercato è il massimo, non il primo che capita.",
        verifica: "Riduci 45/60 e 28/84, e verifica che le due frazioni risultanti abbiano lo stesso denominatore quando sono equivalenti.",
        limite: "Vale per numeratore e denominatore interi non nulli: non si estende a numeratori reali, dove la forma ridotta non è definita.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_01_1",
            testo: "La forma ridotta di una frazione è unica.",
            ancora: Some("span-01-1"),
            testo_span: Some("La stessa quantità ha molte rappresentazioni: 3/6, 2/4 e 1/2 indicano la stessa parte."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "letture/02-divisibilita.html",
        famiglia: F::Letture,
        titolo: "Divisibilità e criteri di divisibilità",
        riassunto: "Quando un intero divide un altro intero, e come si decide senza fare la divisione.",
        paragrafi: &[
            "Un intero a divide b se esiste un intero k tale che b = a·k. La condizione è più forte della divisione con resto: il resto deve essere zero.",
            "I criteri di divisibilità per 2, 3, 5 e 10 dipendono soltanto dalla cifra delle unità o dalla somma delle cifre, e sono la via rapida per verificare senza divisore.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/01-numero-razionale.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: un numero è divisibile per 3 se la somma delle sue cifre lo è. Questo vale per 3 e per 9, e non vale per nessun altro divisore: per 7 la regola non esiste.",
        obiettivi: "Applicare i criteri di divisibilità e giustificare la risposta senza dividere.",
        scala: "Livello 4: usa il criterio e sa dire perché funziona. Livello 3: usa il criterio correttamente. Livello 2: distingue i casi in cui il criterio si applica. Livello 1: divide per tentativi.",
        equivoci: "Non confondere «divisibile per» con «multiplo di»: la relazione è simmetrica solo se si formula bene, e i due insiemi non coincidono.",
        esempio: "1284 ha somma delle cifre 15, quindi è divisibile per 3. Non basta: 15 non è divisibile per 9, quindi 1284 non è divisibile per 9.",
        verifica: "Decidi se 2736 è divisibile per 3, 9 e 4, e motiva ogni risposta con il criterio e non con la divisione.",
        limite: "Il criterio della somma delle cifre vale solo in base 10: in base 7 la somma non ha questo significato.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_02_1",
            testo: "Un intero a è divisibile per 3 se e solo se la somma delle sue cifre è divisibile per 3.",
            ancora: Some("span-02-1"),
            testo_span: Some("I criteri di divisibilità per 2, 3, 5 e 10 dipendono soltanto dalla cifra delle unità o dalla somma delle cifre, e sono la via rapida per verificare senza divisore."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "letture/03-frazione-irriducibile.html",
        famiglia: F::Letture,
        titolo: "La frazione irriducibile e la sua unicità",
        riassunto: "Perché la forma ridotta di una frazione non dipende da come si arriva a ridurla.",
        paragrafi: &[
            "Riducendo con divisori diversi si arriva sempre allo stesso numeratore e allo stesso denominatore: la forma ridotta è unica.",
            "L'unicità viene dal fatto che dividere numeratore e denominatore per lo stesso fattore primo conserva il valore, e la scomposizione in fattori primi non ammette alternative.",
        ],
        stato: S::DelDocente,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/02-divisibilita.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: ridurre due volte con divisori diversi non dà due risultati diversi. Se dà, il primo passaggio era sbagliato.",
        obiettivi: "Dimostrare che la forma ridotta è unica e saperla costruire dalla scomposizione in fattori primi.",
        scala: "Livello 4: dimostra l'unicità. Livello 3: costruisce la forma ridotta. Livello 2: riconosce che la forma ridotta non dipende dalla strada. Livello 1: riduce per tentativi.",
        equivoci: "Non confondere «forma ridotta» con «forma normale»: il numeratore e il denominatore si possono scambiare e il valore cambia.",
        esempio: "84/126: 84 = 2²·3·7, 126 = 2·3²·7, minimo comune fattore 2·3·7 = 42, quindi 2/3.",
        verifica: "Riduci 360/504 per scomposizione in fattori primi e verifica il risultato moltiplicando per 126.",
        limite: "L'unicità vale per coppie di interi; non si parla di forma ridotta per espressioni con variabili.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_03_1",
            testo: "La scomposizione in fattori primi di un intero è unica.",
            ancora: Some("span-03-1"),
            testo_span: Some("L'unicità viene dal fatto che dividere numeratore e denominatore per lo stesso fattore primo conserva il valore, e la scomposizione in fattori primi non ammette alternative."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "letture/04-limite-di-successione.html",
        famiglia: F::Letture,
        titolo: "Il limite di una successione",
        riassunto: "Che cosa significa che una successione converge, e perché non basta guardare i primi termini.",
        paragrafi: &[
            "Una successione converge quando i termini si avvicinano a un numero fissato, che è il limite: per ogni distanza esiste un indice oltre il quale il termine ci resta dentro.",
            "Guardare i primi termini non basta in generale: una successione può avvicinarsi al limite, superarlo e tornare indietro, e la convergenza riguarda il comportamento definitivo, non l'andamento iniziale.",
        ],
        stato: S::Bozza,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/02-divisibilita.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: convergenza non vuol dire «il termine non si muove più», vuol dire che si muove sempre di meno.",
        obiettivi: "Leggere la definizione epsilon-N e distinguere convergenza da comportamento iniziale.",
        scala: "Livello 4: scrive la definizione epsilon-N. Livello 3: verifica la convergenza con stime. Livello 2: distingue successione convergente da divergente. Livello 1: riconosce la convergenza da un grafico.",
        equivoci: "Non confondere «convergente» con «monotona»: una successione convergente può non essere monotona, e una monotona può divergere.",
        esempio: "I termini 1, 1/2, 1/3, 1/4 sono decrescenti in valore assoluto e il loro limite è 0, ma la successione 1, 0, 1, 0 ha lo stesso insieme di termini e non converge.",
        verifica: "Decidi se convergono le successioni dei termini 1/n e (-1)^n, e motiva con la definizione e non con l'intuizione.",
        limite: "Vale per successioni reali: in spazi metrici generali la convergenza richiede che ogni successione di Cauchy converga.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_04_1",
            testo: "Una successione convergente non è necessariamente monotona.",
            ancora: Some("span-04-1"),
            testo_span: Some("Guardare i primi termini non basta in generale: una successione può avvicinarsi al limite, superarlo e tornare indietro, e la convergenza riguarda il comportamento definitivo, non l'andamento iniziale."),
            stato: ClaimStatusKind::Contradicted,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "esercizi/01-somma-di-frazioni.html",
        famiglia: F::Esercizi,
        titolo: "Somma di frazioni con denominatore diverso",
        riassunto: "Esercizio parametrizzato: due istanze diverse, lo stesso ragionamento, risposte diverse.",
        paragrafi: &[
            "L'esercizio è parametrizzato: il seed sceglie i tre interi dell'istanza, e la risposta cambia con il seed. Il ragionamento non cambia mai.",
            "È la ragione per cui copiare il compito del compagno non aiuta: la risposta è diversa e il procedimento è lo stesso, quindi si può copiare il procedimento e non la risposta.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/03-frazione-irriducibile.html"],
        origine: OriginSpec::Generated {
            by: DOCENTE,
            model: "claude-sonnet-4-5",
            prompt_hash: "sha256:1a4f0c9d2b7e",
            generator: "kbs-intake/0.1.0",
        },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: due frazioni si sommano solo dopo averle messe a denominatore comune. Sommare i denominatori non è mai corretto, e la verifica del risultato è una divisione.",
        obiettivi: "Calcolare la somma di due frazioni e ridurre il risultato.",
        scala: "Livello 4: riduce e verifica moltiplicando. Livello 3: calcola correttamente. Livello 2: mette a denominatore comune. Livello 1: moltiplica numeratori e denominatori.",
        equivoci: "Non confondere la somma di due frazioni con la somma dei denominatori, e non dimenticare di ridurre il risultato finale.",
        esempio: "1/2 + 1/3: denominatore comune 6, quindi 3/6 + 2/6 = 5/6. La somma dei denominatori darebbe 5, che non è un numero tra 0 e 1.",
        verifica: "Svolgi le due istanze dell'esercizio e verifica ogni risultato moltiplicandolo per il denominatore comune.",
        limite: "Vale per due addendi. Con più di due, si somma due alla volta e si riduce dopo ogni passaggio.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_05_1",
            testo: "Due istanze dello stesso esercizio hanno risposte diverse e lo stesso ragionamento.",
            ancora: Some("span-05-1"),
            testo_span: Some("È la ragione per cui copiare il compito del compagno non aiuta: la risposta è diversa e il procedimento è lo stesso, quindi si può copiare il procedimento e non la risposta."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[ExerciseSpec {
            id: "ex_05_1",
            famiglia: "somma-frazioni",
            generatore: "kbs-exercise/0.1.0",
            testo: "Calcola 1/a + 1/b e riduci il risultato; il terzo intero c è il fattore comune da estrarre prima.",
            checker: CheckerSpec::Equivalence { normale: "forma ridotta" },
            istanze: &[
                InstanceSpec { seed: "s1", a: 2, b: 3, c: 1, attesa: "5/6" },
                InstanceSpec { seed: "s2", a: 3, b: 4, c: 1, attesa: "7/12" },
            ],
            giudicato_da: Some(GraderKind::Deterministic),
        }],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
];
