//! Tavola degli item, parte 4 di 4: dialoghi, appunti, mappe, produzioni.
//!
//! Qui cadono le due fiastre rotte restanti — il ciclo dei prerequisiti e il
//! riferimento a un CDN esterno — e qui sta la scena 3D, che è l'unico item
//! del banco in cui l'interazione è il rapporto (D15.1).

use crate::contract::Defect;
use crate::families::Family as F;
use crate::spec::*;
use kbs_core::{GraderKind, PublicationState as S};

/// La CDN che l'item rotto referenzia. Il nome è qui perché il referto deve
/// poter dire *che cosa* è stato referenziato, e non solo «qualcosa di
/// esterno».
pub const CDN_ESTERNO: &str = "https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.min.js";

/// Il percorso che l'item sano referenzia: la rotta servita dal binario, che
/// funziona senza rete (D15).
pub const THREE_LOCALE: &str = "/three/three.module.js";

pub const V: &[Spec] = &[
    Spec {
        rel: "dialoghi/01-domande-frequenti.html",
        famiglia: F::Dialoghi,
        titolo: "Le domande che la classe fa ogni anno",
        riassunto: "Il dialogo come ancoraggio, e come materia prima.",
        paragrafi: &[
            "Le domande sono ancorate a quattro livelli: al file, al paragrafo, alla riga e alla parola. L'ancoraggio è ciò che rende la risposta verificabile.",
            "Le domande più frequenti entrano nelle unità successive. È il passaggio più economico di tutto il sistema: il materiale nasce dalla domanda, non dalla pianificazione.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["esercizi/01-somma-di-frazioni.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: ogni domanda è ancorata a un punto preciso del materiale. Una domanda senza ancoraggio non è una domanda, è un dubbio.",
        obiettivi: "Ancorare una domanda e trasformarla in un argomento quando ricorre.",
        scala: "Livello 4: distingue il dubbio che genera un argomento dalla domanda che il materiale già risolve. Livello 3: ancora. Livello 2: distingue i quattro livelli. Livello 1: chiede.",
        equivoci: "Non confondere una domanda frequente con una domanda importante: la frequenza è un conteggio e non un giudizio.",
        esempio: "«Perché si riduce?» è apparsa undici volte con tre ancoraggi diversi. È diventata l'unità sulla forma ridotta, e l'unità porta il conto.",
        verifica: "Scrivi tre domande con il loro livello di ancoraggio e indica quale potrebbe diventare un argomento.",
        limite: "Vale per le domande ancorate al materiale del corso: quelle che non hanno ancoraggio restano fuori dal conteggio.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_28_1",
            testo: "L'ancoraggio a quattro livelli è ciò che rende la risposta a una domanda verificabile.",
            ancora: Some("span-28-1"),
            testo_span: Some("Le domande sono ancorate a quattro livelli: al file, al paragrafo, alla riga e alla parola. L'ancoraggio è ciò che rende la risposta verificabile."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "dialoghi/02-confronto-risposte.html",
        famiglia: F::Dialoghi,
        titolo: "Confronto fra risposte alla stessa domanda",
        riassunto: "Tre risposte alla stessa domanda, e perché differiscono.",
        paragrafi: &[
            "Tre studenti hanno risposto alla stessa domanda di esame con tre strategie diverse, e tutte e tre hanno risposte numericamente giuste.",
            "Il confronto non serve a scegliere la risposta migliore: serve a mostrare che la procedura è ciò che si impara, e che la risposta è la sua conseguenza.",
        ],
        stato: S::DelDocente,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["laboratori/03-dataset-cocola.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: tre risposte giuste, tre procedure diverse. Nessuna delle procedure è quella che avrei scritto io, e questo è il punto del confronto.",
        obiettivi: "Ricostruire la procedura dietro una risposta corretta e confrontarla con un'altra.",
        scala: "Livello 4: sa dire perché la propria procedura è sbagliata. Livello 3: ricostruisce la procedura altrui. Livello 2: distingue procedura e risultato. Livello 1: confronta i numeri.",
        equivoci: "Non confondere correttezza e comprensione: due risposte corrette possono stare dietro due procedure che lo studente non ha capito.",
        esempio: "La seconda risposta riduce per 6 prima di sommare e la terza per 3 dopo. I risultati coincidono, e i due errori futuri sono diversi.",
        verifica: "Ricostruisci la procedura delle tre risposte e indica quale produce l'errore più difficile da notare.",
        limite: "Vale per risposte a procedura ricostruibile: una risposta con un salto non argomentato non si può confrontare.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_29_1",
            testo: "Due risposte corrette possono stare dietro due procedure diverse, e quindi dietro due errori futuri diversi.",
            ancora: Some("span-29-1"),
            testo_span: Some("Il confronto non serve a scegliere la risposta migliore: serve a mostrare che la procedura è ciò che si impara, e che la risposta è la sua conseguenza."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "dialoghi/03-annotazioni-docente.html",
        famiglia: F::Dialoghi,
        titolo: "Annotazioni del docente sulle elaborati",
        riassunto: "Le annotazioni che sopravvivono all'elaborato, e la regola di conservazione.",
        paragrafi: &[
            "Ogni annotazione è ancorata a un punto dell'elaborato e porta l'identità di chi l'ha scritta. Le annotazioni sopravvivono all'elaborato e l'elaborato può sopravvivere alle annotazioni.",
            "La regola di conservazione è dichiarata e non implicita: le annotazioni si conservano finché esiste l'elaborato, e non oltre. Nessuna conservazione automatica per minori.",
        ],
        stato: S::Archiviato,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["rubriche/01-rubrica-tesina.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: le annotazioni del docente sono parte del registro e non del materiale didattico. Non si distribuiscono e non finiscono in un indice condiviso.",
        obiettivi: "Ancorare un'annotazione e applicare la regola di conservazione dichiarata.",
        scala: "Livello 4: sa quando un'annotazione è operativa e quando è personale. Livello 3: ancora e conserva. Livello 2: distingue annotazione e voto. Livello 1: annota.",
        equivoci: "Non confondere annotazione e voto: l'annotazione spiega, il voto classifica, e solo il secondo va sulla pagella.",
        esempio: "L'annotazione «rifletti sul passaggio dal terzo al quarto punto» è operativa e va conservata; «bravo» è personale e va letta una volta sola.",
        verifica: "Applica la regola di conservazione a tre annotazioni e indica quale non sarebbe dovuta sopravvivere.",
        limite: "Vale per le annotazioni ancorate a un elaborato: un commento libero non ha ancoraggio e quindi non è conservato.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_30_1",
            testo: "Le annotazioni del docente non entrano nell'indice condiviso.",
            ancora: Some("span-30-1"),
            testo_span: Some("Ogni annotazione è ancorata a un punto dell'elaborato e porta l'identità di chi l'ha scritta. Le annotazioni sopravvivono all'elaborato e l'elaborato può sopravvivere alle annotazioni."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "appunti/01-schema-di-ripasso.html",
        famiglia: F::Appunti,
        titolo: "Schema di ripasso compilato dallo studente",
        riassunto: "Gli appunti che diventano didattici solo dopo essere stati rielaborati.",
        paragrafi: &[
            "Lo schema ha quattro caselle: definizione, esempio, controesempio, domanda aperta. Le prime tre si compilano dalla lezione, la quarta no.",
            "Gli appunti presi durante la lezione sono attivi e non didattici. Diventano didattici quando lo studente li rielabora, e il sistema non può misurare la rielaborazione.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["mazzi/01-mazzo-frazioni.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: la casella «domanda aperta» non si compila dalla lezione. Se la compili copiando, lo schema è vuoto e sembra pieno.",
        obiettivi: "Compilare lo schema e riconoscere quale casella richiede rielaborazione.",
        scala: "Livello 4: sa riconoscere la casella copiata da quella rielaborata. Livello 3: compila le tre caselle dalla lezione. Livello 2: distingue definizione ed esempio. Livello 1: prende appunti.",
        equivoci: "Non confondere appunti e schema: lo schema è uno strumento con quattro caselle, e negli appunti non ci sono caselle.",
        esempio: "Definizione: copia la lezione. Esempio: copia la lezione. Controesempio: non c'è in lezione. Domanda aperta: dipende da te.",
        verifica: "Compila lo schema e verifica che la casella del controesempio non sia una riformulazione della definizione.",
        limite: "Vale per argomenti che hanno un controesempio chiaro: per altri argomenti la casella resta vuota e va tenuta vuota.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_31_1",
            testo: "Gli appunti presi durante la lezione sono attivi e diventano didattici dopo la rielaborazione.",
            ancora: Some("span-31-1"),
            testo_span: Some("Gli appunti presi durante la lezione sono attivi e non didattici. Diventano didattici quando lo studente li rielabora, e il sistema non può misurare la rielaborazione."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "appunti/02-appunti-lezione.html",
        famiglia: F::Appunti,
        titolo: "Appunti di lezione: il costo dell'essere passivi",
        riassunto: "Il formato più recuperabile del catalogo e uno dei meno utili.",
        paragrafi: &[
            "Gli appunti sono testo, e quindi sono recuperabili per intero. È il caso migliore del catalogo sul piano dell'estrazione e uno dei peggiori sul piano dell'uso.",
            "Un appunti ben preso non trasforma l'ascolto in apprendimento. Non c'è componente aggiuntivo che lo faccia, e un chatbot davanti agli appunti non lo cambia.",
        ],
        stato: S::Bozza,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["letture/02-divisibilita.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: prendere appunti bene non è studiare. Se il tuo obiettivo è passare il compito, questi appunti ti servono; se è capire, ti manca il passaggio finale.",
        obiettivi: "Riconoscere il costo dell'oggetto più recuperabile e più passivo del catalogo.",
        scala: "Livello 4: sa trasformare gli appunti in schema e sa dire che cosa ha perso. Livello 3: distingue appunti e schema. Livello 2: prende appunti. Livello 1: copia.",
        equivoci: "Non confondere recuperabilità e utilità: gli appunti sono interamente recuperabili e quasi inutili da soli.",
        esempio: "Gli appunti di una lezione di un'ora sono dodici facce di carta. Il costo del passaggio da facce a schema è di circa mezz'ora, e nessuno lo fa durante la lezione.",
        verifica: "Trasforma gli appunti della lezione in schema e annota il tempo che ci hai messo: è il costo che nessuno misura.",
        limite: "Vale per appunti di lezioni parlate: un appunto di un esperimento contiene la procedura e non può essere trasformato in schema.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_32_1",
            testo: "Un appunto ben preso non trasforma l'ascolto in apprendimento.",
            ancora: Some("span-32-1"),
            testo_span: Some("Un appunto ben preso non trasforma l'ascolto in apprendimento. Non c'è componente aggiuntivo che lo faccia, e un chatbot davanti agli appunti non lo cambia."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "appunti/03-appunti-3d.html",
        famiglia: F::Appunti,
        titolo: "Appunti presi sulla scena 3D",
        riassunto: "Che cosa si annota guardando una scena, e che cosa si perde girandola.",
        paragrafi: &[
            "Dopo aver girato la scena del parallelepipedo, gli appunti dello studente contengono i nomi delle facce e nessuna delle relazioni.",
            "È il difetto noto dell'estrazione di relazioni dalle figure, e in 3D è lo stesso difetto: i nodi vengono prima e gli archi dopo. Le figure danno abbondanza, non qualità.",
        ],
        stato: S::DelDocente,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["mappe/04-scena-3d-parallelepipedo.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: girare la scena non è guardare la scena. Se annoti mentre ruoti, annoti i nomi; le relazioni richiedono che tu decida quale sia.",
        obiettivi: "Distinguere ciò che si annota da ciò che si indovina davanti a una figura.",
        scala: "Livello 4: sa quale relazione non si vede e perché. Livello 3: annota i nodi. Livello 2: sa che gli archi sono il punto debole. Livello 1: gira.",
        equivoci: "Non confondere una relazione plausibile e una relazione verificata: davanti a una figura, la plausibilità è la regola e la verifica l'eccezione.",
        esempio: "I nodi della scena sono faccia, spigolo e vertice: sono evidenti. Gli archi sono confine, terminazione e appartenenza: sono deduzioni.",
        verifica: "Annota la scena e conta quanti archi hai scritto rispetto ai nodi: il rapporto dice quanto hai indovinato.",
        limite: "Vale per scene con relazioni dichiarate: senza claim per arco, nessuna deduzione dello studente è verificabile.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_33_1",
            testo: "Davanti a una figura, la plausibilità di una relazione è la regola e la verifica è l'eccezione.",
            ancora: Some("span-33-1"),
            testo_span: Some("È il difetto noto dell'estrazione di relazioni dalle figure, e in 3D è lo stesso difetto: i nodi vengono prima e gli archi dopo. Le figure danno abbondanza, non qualità."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "mappe/01-ciclo-di-vita.html",
        famiglia: F::Mappe,
        titolo: "Mappa del ciclo di vita di un documento",
        riassunto: "Una mappa generata, e perché i suoi archi valgono meno dei suoi nodi.",
        paragrafi: &[
            "Il documento nasce in bozza, viene verificato, entra in uso e viene archiviato. I quattro stati sono i nodi della mappa e le transizioni sono gli archi.",
            "La mappa è generata dal sistema, e quindi è più abbondante e non migliore: gli archi sono transizioni automatiche, non relazioni che qualcuno abbia pensato.",
        ],
        stato: S::DelDocente,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["dialoghi/02-confronto-risposte.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: gli archi di questa mappa sono automatici. Se cerchi il perché di una transizione, non è qui: è nel registro.",
        obiettivi: "Leggere una mappa generata e distinguere gli archi automatici da quelli argomentati.",
        scala: "Livello 4: sa che una mappa generata abbonda e non migliora. Livello 3: legge le transizioni. Livello 2: conosce i quattro stati. Livello 1: guarda la mappa.",
        equivoci: "Non confondere un arco generato con un arco verificato: il primo è la transizione avvenuta, il secondo è una relazione che qualcuno ha dichiarato.",
        esempio: "L'arco da bozza a verificato è un arco generato: esiste perché qualcuno ha cliccato. L'arco «prerequisito» è dichiarato e ha uno span.",
        verifica: "Indica quanti archi della mappa sono generati e quanti dichiarati, e spiega come lo sai.",
        limite: "Vale per le transizioni registrate: una transizione avvenuta fuori dal sistema non compare e quindi non è un arco mancante.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_34_1",
            testo: "Gli archi di una mappa generata sono transizioni automatiche, non relazioni dichiarate.",
            ancora: Some("span-34-1"),
            testo_span: Some("La mappa è generata dal sistema, e quindi è più abbondante e non migliore: gli archi sono transizioni automatiche, non relazioni che qualcuno abbia pensato."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    Spec {
        rel: "mappe/02-mappa-argomentale-terza.html",
        famiglia: F::Mappe,
        titolo: "Mappa argomentale della terza media",
        riassunto: "La mappa che lo studente corregge, e che vale per quello.",
        paragrafi: &[
            "La mappa ha undici nodi e quattordici archi, e ogni arco porta la persona che lo ha dichiarato. Lo studente può togliere un arco e proporne un altro.",
            "È il caso in cui l'interazione è il rapporto: senza correzione la mappa è un'immagine, con correzione è un esercizio. Le due cose hanno lo stesso valore di disegno e valori didattici diversi.",
        ],
        stato: S::InCorso,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["mappe/01-ciclo-di-vita.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: togliere un arco è un atto serio. Se lo togli e non ne proponi un altro, l'argomento ha un buco e tu hai peggiorato la mappa.",
        obiettivi: "Correggere un arco dichiarato da un pari e proporne un altro con la propria giustificazione.",
        scala: "Livello 4: distingue un arco falso da un arco irrilevante. Livello 3: corregge e ripropone. Livello 2: sa che cosa è un arco. Livello 1: guarda la mappa.",
        equivoci: "Non confondere un arco falso con un arco non motivato: il primo è sbagliato, il secondo è soltanto non dichiarato.",
        esempio: "L'arco «le frazioni servono per la divisione» è vero e non serve all'argomento della mappa: è un arco irrilevante, e va tolto senza sostituirlo.",
        verifica: "Togli un arco e proponi il tuo, indicando quale fatto del materiale li sostiene entrambi.",
        limite: "Vale per archi con una claim: un arco senza claim non è correggibile, perché non c'è niente da verificare.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_35_1",
            testo: "Senza correzione dell'utente una mappa è un'immagine, non un esercizio.",
            ancora: Some("span-35-1"),
            testo_span: Some("È il caso in cui l'interazione è il rapporto: senza correzione la mappa è un'immagine, con correzione è un esercizio. Le due cose hanno lo stesso valore di disegno e valori didattici diversi."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    // ── Fiastra rotta n. 3: il grafo dei prerequisiti ha un ciclo. L'argomento
    //    si dichiara prerequisito di sé stesso, e l'item non entra. È il ciclo
    //    minimo, scelto per una ragione: un ciclo fra più item lascerebbe,
    //    dopo il rifiuto, un prerequisito pendente su un item che non esiste
    //    più, e il banco dovrebbe assumere una semantica del negozio che
    //    nessun codice di questo repository definisce. Un auto-ciclo non
    //    lascia pendenti e chiude la porta su ogni ciclo più lungo, che è lo
    //    stesso cammino di visita.
    Spec {
        rel: "mappe/03-catena-dei-prerequisiti.html",
        famiglia: F::Mappe,
        titolo: "Catena dei prerequisiti di un argomento",
        riassunto: "Unità che si dichiara prerequisito di sé stessa: il ciclo che non entra.",
        paragrafi: &[
            "La catena mostra che cosa occorre prima di che cosa. In questo item la dichiarazione è sbagliata: il prerequisito puntato è lo stesso item.",
            "Un argomento che richiede sé stesso non ha un punto d'ingresso, e quindi non è insegnabile. Non è un problema di ordine di lettura: è un problema di esistenza.",
        ],
        stato: S::Bozza,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["mappe/03-catena-dei-prerequisiti.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: una catena di prerequisiti che torna su sé stessa non ha primo nodo. Il primo nodo è l'unica cosa che rende una catena leggibile in ordine.",
        obiettivi: "Riconoscere che un grafo di prerequisiti deve essere aciclico e che il primo nodo è ciò che lo rende leggibile.",
        scala: "Livello 4: sa dire perché un auto-ciclo non ha punto d'ingresso. Livello 3: controlla che la catena non torni indietro. Livello 2: sa che cosa è un prerequisito. Livello 1: guarda la catena.",
        equivoci: "Non confondere «la catena è lunga» e «la catena è ciclica»: la lunghezza è un fatto, il ciclo è un difetto.",
        esempio: "a prima di b prima di c prima di a: leggendo non si comincia. Togliere un anello qualunque rende la catena leggibile, e la catena senza un anello è un altro grafo.",
        verifica: "Indica il primo nodo di una catena di cinque nodi e spiega che cosa succede se un nodo ha due padri.",
        limite: "Vale per grafi di prerequisiti: la stessa struttura con nodi e archi invertiti non è un grafo di prerequisiti e ha regole diverse.",
        difetto: Defect::PrerequisitoCiclico("mappe/03-catena-dei-prerequisiti.html"),
        claims: &[ClaimSpec {
            id: "cl_36_1",
            testo: "Un auto-ciclo non ha punto d'ingresso nel grafo dei prerequisiti.",
            ancora: Some("span-36-1"),
            testo_span: Some("Un argomento che richiede sé stesso non ha un punto d'ingresso, e quindi non è insegnabile. Non è un problema di ordine di lettura: è un problema di esistenza."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Docente { by: DOCENTE_2 },
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    // ── La scena 3D. D15.1: un oggetto senza claim non entra nell'indice
    //    condiviso, e nessuna risposta visibile nella scena (D8 vale anche
    //    per 3D: il GUARDIAN non può essere solo un vincolo testuale mentre la
    //    risposta è un oggetto ruotabile). Qui le relazioni che lo studente
    //    corregge sono dichiarate come `correggibili`, ed è su quelle che si
    //    misura il guadagno pedagogico.
    Spec {
        rel: "mappe/04-scena-3d-parallelepipedo.html",
        famiglia: F::Mappe,
        titolo: "Scena 3D: facce, spigoli e vertici di un parallelepipedo",
        riassunto: "La scena che si manipola invece di guardare, e le cui relazioni sono tutte dichiarate.",
        paragrafi: &[
            "La scena mostra un parallelepipedo con tre classi di oggetti: le facce, gli spigoli e i vertici. Ogni oggetto dichiarato corrisponde a un'affermazione con il proprio testo di sostegno.",
            "Lo studente non guarda la scena: la gira e corregge le relazioni. Il guadagno che si registra è il tempo di manipolazione e il numero di relazioni corrette, non il tempo sul compito.",
        ],
        stato: S::InCorso,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["laboratori/03-dataset-cocola.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: nessuna risposta è visibile nella scena. Il numero di facce, spigoli e vertici è ciò che devi ottenere manipolando, e la scena non te lo mostra. Il rendering è un effetto: puoi cambiare camera e luce, e i dati non cambiano.",
        obiettivi: "Contare facce, spigoli e vertici manipolando la scena, e correggere almeno una relazione dichiarata.",
        scala: "Livello 4: corregge una relazione e sa dire quale fatto la smentirebbe. Livello 3: conta e corregge. Livello 2: conta girando la scena. Livello 1: guarda e indovina.",
        equivoci: "Non confondere il numero di oggetti visibili con il numero di oggetti: la scena mostra una faccia per volta, e il totale si ottiene contando le ripetizioni.",
        esempio: "Un parallelepipedo ha sei facce, dodici spigoli e otto vertici: nessuno dei tre numeri si legge guardando la scena da un angolo, e tutti e tre si ottengono contando.",
        verifica: "Manipola la scena fino a ricavare i tre numeri, poi correggi la relazione che ritieni sbagliata e indica il fatto che ti smentisce.",
        limite: "Vale per la scena e per la versione dichiarata del runtime: con un renderer diverso la resa cambia e i dati restano, e il limite è proprio questo.",
        difetto: Defect::Nessuno,
        claims: &[
            ClaimSpec {
                id: "cl_37_1",
                testo: "Un parallelepipedo ha sei facce.",
                ancora: Some("span-37-1"),
                testo_span: Some("La scena mostra un parallelepipedo con tre classi di oggetti: le facce, gli spigoli e i vertici. Ogni oggetto dichiarato corrisponde a un'affermazione con il proprio testo di sostegno."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
            ClaimSpec {
                id: "cl_37_2",
                testo: "Un parallelepipedo ha dodici spigoli.",
                ancora: Some("span-37-2"),
                testo_span: Some("Lo studente non guarda la scena: la gira e corregge le relazioni. Il guadagno che si registra è il tempo di manipolazione e il numero di relazioni corrette, non il tempo sul compito."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
            ClaimSpec {
                id: "cl_37_3",
                testo: "Un parallelepipedo ha otto vertici.",
                ancora: Some("span-37-3"),
                testo_span: Some("Un parallelepipedo ha sei facce, dodici spigoli e otto vertici: nessuno dei tre numeri si legge guardando la scena da un angolo, e tutti e tre si ottengono contando."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
            ClaimSpec {
                id: "cl_37_4",
                testo: "Ogni faccia è delimitata da spigoli.",
                ancora: Some("span-37-4"),
                testo_span: Some("La scena mostra un parallelepipedo con tre classi di oggetti: le facce, gli spigoli e i vertici. Ogni oggetto dichiarato corrisponde a un'affermazione con il proprio testo di sostegno."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
            ClaimSpec {
                id: "cl_37_5",
                testo: "Ogni spigolo termina in due vertici.",
                ancora: Some("span-37-5"),
                testo_span: Some("Lo studente non guarda la scena: la gira e corregge le relazioni. Il guadagno che si registra è il tempo di manipolazione e il numero di relazioni corrette, non il tempo sul compito."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
            ClaimSpec {
                id: "cl_37_6",
                testo: "Ogni vertice appartiene a più di una faccia.",
                ancora: Some("span-37-6"),
                testo_span: Some("Un parallelepipedo ha sei facce, dodici spigoli e otto vertici: nessuno dei tre numeri si legge guardando la scena da un angolo, e tutti e tre si ottengono contando."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
        ],
        esercizi: &[ExerciseSpec {
            id: "ex_37_1",
            famiglia: "conta-nodi-scena",
            generatore: "kbs-exercise/0.1.0",
            testo: "Manipola la scena e indica quante classi di oggetti hai contato; la risposta è un numero e il checker confronta il numero.",
            checker: CheckerSpec::Numeric { tolerance: 0.0 },
            istanze: &[InstanceSpec { seed: "s1", a: 6, b: 12, c: 8, attesa: "3" }],
            giudicato_da: Some(GraderKind::Deterministic),
        }],
        scena: Some(SceneSpec {
            manifest: "scene/parallelepipedo.json",
            titolo: "Parallelepipedo: facce, spigoli, vertici",
            nodi: &[
                SceneNode { id: "n-faccia", etichetta: "faccia", claim: "cl_37_1", correggibile: false, x: 0.0, y: 1.0, z: 0.0 },
                SceneNode { id: "n-spigolo", etichetta: "spigolo", claim: "cl_37_2", correggibile: false, x: 1.0, y: 0.5, z: 0.0 },
                SceneNode { id: "n-vertice", etichetta: "vertice", claim: "cl_37_3", correggibile: false, x: 0.5, y: 0.0, z: 0.5 },
            ],
            archi: &[
                SceneEdge { id: "a-confine", da: "n-faccia", a: "n-spigolo", relazione: "delimitata da", claim: "cl_37_4", correggibile: true },
                SceneEdge { id: "a-terminazione", da: "n-spigolo", a: "n-vertice", relazione: "termina in", claim: "cl_37_5", correggibile: true },
                SceneEdge { id: "a-appartenenza", da: "n-vertice", a: "n-faccia", relazione: "appartiene a", claim: "cl_37_6", correggibile: false },
            ],
        }),
        riferimento_esterno: None,
        carica_three_locale: true,
    },
    // ── Fiastra rotta n. 4: la scena che chiama fuori dal perimetro. La stessa
    //    scena, la stessa struttura, l'import sbagliato. D15: la sua violazione
    //    impedisce la pubblicazione, perché un artifact che chiama fuori non è
    //    verificabile (D6) né riproducibile (D11).
    Spec {
        rel: "mappe/05-scena-3d-da-cdn.html",
        famiglia: F::Mappe,
        titolo: "Scena 3D importata da una CDN",
        riassunto: "La stessa scena, caricata da fuori: in una classe senza rete non esiste.",
        paragrafi: &[
            "Questa versione della scena importa three.js da una CDN pubblica. Funziona sulla rete del laboratorio e non funziona in nessuna classe che non ce l'ha.",
            "Non è un dettaglio: è una rotta dati che esce dal perimetro, un punto di fallimento a rialbero, e un ostacolo all'esercizio offline. Per questo l'unità non pubblica.",
        ],
        stato: S::Bozza,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["laboratori/03-dataset-cocola.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: questa scena non funziona senza rete. Se la tua classe non ha connessione, l'unità è vuota e nessun messaggio te lo dirà.",
        obiettivi: "Riconoscere che un'importazione da CDN è una rotta dati fuori dal perimetro.",
        scala: "Livello 4: sa dire che cosa dell'unità non è verificabile se il runtime cambia. Livello 3: riconosce la dipendenza esterna. Livello 2: sa che serve la rete. Livello 1: apre la pagina.",
        equivoci: "Non confondere «la pagina si apre» e «l'unità è utilizzabile»: la prima dipende dalla rete del momento.",
        esempio: "Il banco di prova contiene due versioni della stessa scena: una che importa da `/three/three.module.js` e una che importa da una CDN. Solo la prima passa.",
        verifica: "Apri la scena senza rete e descrivi che cosa manca, poi apri la versione locale e confronta.",
        limite: "Vale per l'ambiente senza rete: in un'aula collegata la pagina funziona, e proprio per questo il difetto è invisibile durante la verifica.",
        difetto: Defect::RiferimentoEsterno(CDN_ESTERNO),
        claims: &[
            ClaimSpec {
                id: "cl_38_1",
                testo: "Un'importazione da CDN è una rotta dati che esce dal perimetro.",
                ancora: Some("span-38-1"),
                testo_span: Some("Non è un dettaglio: è una rotta dati che esce dal perimetro, un punto di fallimento a rialbero, e un ostacolo all'esercizio offline. Per questo l'unità non pubblica."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
            ClaimSpec {
                id: "cl_38_2",
                testo: "La scena ha gli stessi dati della versione locale, e la sola differenza è l'origine del runtime.",
                ancora: Some("span-38-2"),
                testo_span: Some("Questa versione della scena importa three.js da una CDN pubblica. Funziona sulla rete del laboratorio e non funziona in nessuna classe che non ce l'ha."),
                stato: ClaimStatusKind::Supported,
                emittente: EmittenteSpec::Contenuto,
            },
        ],
        esercizi: &[],
        scena: Some(SceneSpec {
            manifest: "scene/da-cdn.json",
            titolo: "Parallelepipedo: versione con runtime esterno",
            nodi: &[SceneNode {
                id: "n-faccia",
                etichetta: "faccia",
                claim: "cl_38_2",
                correggibile: false,
                x: 0.0,
                y: 1.0,
                z: 0.0,
            }],
            archi: &[SceneEdge {
                id: "a-dipendenza",
                da: "n-faccia",
                a: "n-faccia",
                relazione: "caricata da",
                claim: "cl_38_1",
                correggibile: false,
            }],
        }),
        riferimento_esterno: Some(CDN_ESTERNO),
        carica_three_locale: false,
    },
    Spec {
        rel: "produzioni/01-video-didattico.html",
        famiglia: F::Produzioni,
        titolo: "Produzione video: spiegare a un altro",
        riassunto: "La produzione che non è recuperabile, e che vale più di tutto il resto.",
        paragrafi: &[
            "Il compito è spiegare a un compagno un argomento e ricevere da lui la domanda di ritorno. La comprensione è ciò che l'oggetto contiene, e la comprensione non è nel segnale.",
            "Si può sapere che lo studente ha parlato e che cosa ha detto. Non si può sapere che cosa stava pensando, e nessuna quantità di lavoro automatico recupera l'inferenza.",
        ],
        stato: S::InCorso,
        corso: CORSO_MATEMATICA,
        prerequisiti: &["video/01-diminuzione-derivate.html"],
        origine: OriginSpec::Human { by: DOCENTE },
        ratifica: RatificaSpec::Fresca,
        guardian: "Prima di leggere: il sistema vedrà la trascrizione del tuo video e non vedrà se hai capito. Se ti senti valutato dal caricamento, hai letto il contratto al contrario.",
        obiettivi: "Spiegare un argomento a un pari e raccogliere la domanda che la spiegazione non chiude.",
        scala: "Livello 4: usa la domanda ricevuta per correggere la spiegazione e la ripete. Livello 3: spiega e raccoglie. Livello 2: registra il video. Livello 1: guarda.",
        equivoci: "Non confondere «ho registrato» e «ho spiegato»: la registrazione è l'atto del sistema, la spiegazione è il tuo.",
        esempio: "Uno studente che rispiega la forma ridotta in due minuti riceve la domanda «e se il denominatore è zero?». Quella domanda è il compito vero.",
        verifica: "Registra la spiegazione, annota la domanda di ritorno e rispondi in un secondo video di un minuto.",
        limite: "Vale per l'oggetto multimediale: è l'unico del catalogo che non è recuperabile, e per questo l'unità non entra in nessun indice.",
        difetto: Defect::Nessuno,
        claims: &[ClaimSpec {
            id: "cl_39_1",
            testo: "La comprensione non è nel segnale, e quindi non è recuperabile.",
            ancora: Some("span-39-1"),
            testo_span: Some("Si può sapere che lo studente ha parlato e che cosa ha detto. Non si può sapere che cosa stava pensando, e nessuna quantità di lavoro automatico recupera l'inferenza."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
    // ── Fiastra rotta n. 5: il contratto supera l'hard cap di 8 192 byte.
    //    Il contenuto del podcast è banale e il difetto è solo nel contratto:
    //    è la prova che la validazione guarda il contratto e non l'argomento,
    //    e che un buon podcast non si salva da un contratto troppo lungo.
    Spec {
        rel: "produzioni/02-podcast-di-classe.html",
        famiglia: F::Produzioni,
        titolo: "Podcast di classe: interviste agli studenti",
        riassunto: "Unità dal contratto troppo lungo: il cap di 8 192 byte è un contratto di formato, non un consiglio.",
        paragrafi: &[
            "Il podcast raccoglie brevi interviste a studenti su che cosa ricordano di un argomento. Le interviste sono brevi e citano l'argomento di cui parlano.",
            "Il difetto è nel contratto, che non entra nel formato. Non c'è modo di accorciarlo senza perdere un vincolo, e quindi l'unità non pubblica finché non lo si riscrive.",
        ],
        stato: S::DelDocente,
        corso: CORSO_INFORMATICA,
        prerequisiti: &["video/03-audio-glossario.html"],
        origine: OriginSpec::Human { by: DOCENTE_2 },
        ratifica: RatificaSpec::Nessuna,
        guardian: "Prima di leggere: ogni intervista dice a quale argomento si riferisce. Senza quel riferimento l'ascolto è piacevole e non è consultabile.",
        obiettivi: "Riconoscere che un podcast entra in archivio come trascrizione e che cosa di un podcast resta fuori.",
        scala: "Livello 4: sa dire che cosa di un'intervista non è recuperabile. Livello 3: distingue intervista e trascrizione. Livello 2: ascolta. Livello 1: sa che il podcast esiste.",
        equivoci: "Non confondere la durata dell'intervista e il suo valore didattico: venti minuti di racconto continuo non dicono nulla che una risposta sola non dica.",
        esempio: "L'intervista migliore dura quaranta secondi e dice «non ricordo perché si riduce, ricordo che si divide per qualcosa». Le altre venti minuti non aggiungono niente a questa frase.",
        verifica: "Ascolta due interviste e annota quale delle due contiene un riferimento esplicito all'argomento.",
        limite: "Vale per interviste brevi: un podcast lungo con più ospiti non entra nel modello, e il banco non lo copre.",
        difetto: Defect::OltreBudget,
        claims: &[ClaimSpec {
            id: "cl_40_1",
            testo: "Un podcast entra in archivio come trascrizione, e come nient'altro.",
            ancora: Some("span-40-1"),
            testo_span: Some("Il podcast raccoglie brevi interviste a studenti su che cosa ricordano di un argomento. Le interviste sono brevi e citano l'argomento di cui parlano."),
            stato: ClaimStatusKind::Supported,
            emittente: EmittenteSpec::Contenuto,
        }],
        esercizi: &[],
        scena: None,
        riferimento_esterno: None,
        carica_three_locale: false,
    },
];
